/**
 * Test code generator
 *
 * Generates Playwright or Cypress test code from captured dataLayer events
 */

import type { DataLayerEvent } from "../types";
import {
  TEST_FRAMEWORK,
  ASSERTION_STYLE,
  type TestFramework,
  type AssertionStyle,
  type TestGeneratorOptions,
  type GeneratedTest,
} from "../types/test-generator";

/**
 * Generate test code from events
 */
export function generateTestCode(
  events: readonly DataLayerEvent[],
  options: TestGeneratorOptions
): GeneratedTest {
  const { framework } = options;

  const code =
    framework === TEST_FRAMEWORK.PLAYWRIGHT
      ? generatePlaywrightTest(events, options)
      : generateCypressTest(events, options);

  const extension = framework === TEST_FRAMEWORK.PLAYWRIGHT ? ".spec.ts" : ".cy.js";
  const filename = `datalayer-${slugify(options.testName)}${extension}`;

  return { code, filename, framework };
}

/**
 * Generate Playwright test (TypeScript)
 */
function generatePlaywrightTest(
  events: readonly DataLayerEvent[],
  options: TestGeneratorOptions
): string {
  const { testName, includeNavigation, includeWaits, url, assertionStyle } = options;

  const lines: string[] = [
    "// Generated by Strata - dataLayer Inspector",
    'import { test, expect } from "@playwright/test";',
    "",
    `test("${escapeString(testName)}", async ({ page }) => {`,
  ];

  // Navigation
  if (includeNavigation && url) {
    lines.push(`  await page.goto("${escapeString(url)}");`);
    if (includeWaits) {
      lines.push('  await page.waitForLoadState("networkidle");');
    }
    lines.push("");
  }

  // Get dataLayer
  lines.push("  // Get dataLayer from page");
  lines.push("  const dataLayer = await page.evaluate(() => window.dataLayer || []);");
  lines.push("");

  // Generate assertions for each event
  for (const event of events) {
    const eventName = event.eventName ?? "push";
    const varName = camelCase(eventName) + "Event";

    lines.push(`  // Assert: ${eventName} event`);

    if (event.eventName) {
      lines.push(
        `  const ${varName} = dataLayer.find((e: any) => e.event === "${escapeString(event.eventName)}");`
      );
      lines.push(`  expect(${varName}).toBeDefined();`);
    } else {
      lines.push(`  // Push without event name - check data exists in dataLayer`);
      const dataStr = JSON.stringify(event.data);
      lines.push(
        `  const ${varName} = dataLayer.find((e: any) => JSON.stringify(e).includes(${JSON.stringify(dataStr.slice(0, 50))}));`
      );
    }

    // Generate assertions for data
    const assertions = generateAssertions(event.data, varName, assertionStyle, "playwright");
    lines.push(...assertions.map((a) => `  ${a}`));
    lines.push("");
  }

  lines.push("});");
  lines.push("");

  return lines.join("\n");
}

/**
 * Generate Cypress test (JavaScript)
 */
function generateCypressTest(
  events: readonly DataLayerEvent[],
  options: TestGeneratorOptions
): string {
  const { testName, includeNavigation, includeWaits, url, assertionStyle } = options;

  const lines: string[] = [
    "// Generated by Strata - dataLayer Inspector",
    "",
    `describe("${escapeString(testName)}", () => {`,
    `  it("should fire expected dataLayer events", () => {`,
  ];

  // Navigation
  if (includeNavigation && url) {
    lines.push(`    cy.visit("${escapeString(url)}");`);
    if (includeWaits) {
      lines.push('    cy.wait(2000); // Wait for SPA to load');
    }
    lines.push("");
  }

  // Get dataLayer
  lines.push("    cy.window().then((win) => {");
  lines.push("      const dataLayer = win.dataLayer || [];");
  lines.push("");

  // Generate assertions for each event
  for (const event of events) {
    const eventName = event.eventName ?? "push";
    const varName = camelCase(eventName) + "Event";

    lines.push(`      // Assert: ${eventName} event`);

    if (event.eventName) {
      lines.push(
        `      const ${varName} = dataLayer.find((e) => e.event === "${escapeString(event.eventName)}");`
      );
      lines.push(`      expect(${varName}).to.exist;`);
    } else {
      lines.push(`      // Push without event name`);
      lines.push(`      const ${varName} = dataLayer[${event.index}];`);
    }

    // Generate assertions for data
    const assertions = generateAssertions(event.data, varName, assertionStyle, "cypress");
    lines.push(...assertions.map((a) => `      ${a}`));
    lines.push("");
  }

  lines.push("    });");
  lines.push("  });");
  lines.push("});");
  lines.push("");

  return lines.join("\n");
}

/**
 * Generate assertions for an object
 */
function generateAssertions(
  data: Record<string, unknown>,
  varName: string,
  style: AssertionStyle,
  framework: TestFramework
): string[] {
  const assertions: string[] = [];

  for (const [key, value] of Object.entries(data)) {
    // Skip internal GTM keys
    if (key.startsWith("gtm.")) continue;
    if (key === "event") continue; // Already checked

    const path = `${varName}.${key}`;

    if (value === null) {
      assertions.push(assertNull(path, framework));
    } else if (Array.isArray(value)) {
      assertions.push(...assertArray(path, value, style, framework));
    } else if (typeof value === "object") {
      assertions.push(...assertObject(path, value as Record<string, unknown>, style, framework));
    } else {
      assertions.push(assertPrimitive(path, value, style, framework));
    }
  }

  return assertions;
}

function assertNull(path: string, framework: TestFramework): string {
  return framework === TEST_FRAMEWORK.PLAYWRIGHT
    ? `expect(${path}).toBeNull();`
    : `expect(${path}).to.be.null;`;
}

function assertArray(
  path: string,
  value: unknown[],
  style: AssertionStyle,
  framework: TestFramework
): string[] {
  const assertions: string[] = [];

  if (framework === TEST_FRAMEWORK.PLAYWRIGHT) {
    assertions.push(`expect(Array.isArray(${path})).toBe(true);`);
    if (style === ASSERTION_STYLE.EXACT) {
      assertions.push(`expect(${path}).toHaveLength(${value.length});`);
    }
  } else {
    assertions.push(`expect(${path}).to.be.an("array");`);
    if (style === ASSERTION_STYLE.EXACT) {
      assertions.push(`expect(${path}).to.have.length(${value.length});`);
    }
  }

  // Check first item structure if exists
  if (value.length > 0 && typeof value[0] === "object" && value[0] !== null) {
    const itemPath = `${path}[0]`;
    const itemAssertions = generateAssertions(
      value[0] as Record<string, unknown>,
      itemPath,
      style,
      framework
    );
    assertions.push(...itemAssertions);
  }

  return assertions;
}

function assertObject(
  path: string,
  value: Record<string, unknown>,
  style: AssertionStyle,
  framework: TestFramework
): string[] {
  const assertions: string[] = [];

  if (framework === TEST_FRAMEWORK.PLAYWRIGHT) {
    assertions.push(`expect(${path}).toBeDefined();`);
  } else {
    assertions.push(`expect(${path}).to.exist;`);
  }

  // Recurse into nested object
  for (const [key, nestedValue] of Object.entries(value)) {
    const nestedPath = `${path}.${key}`;

    if (nestedValue === null) {
      assertions.push(assertNull(nestedPath, framework));
    } else if (Array.isArray(nestedValue)) {
      assertions.push(...assertArray(nestedPath, nestedValue, style, framework));
    } else if (typeof nestedValue === "object") {
      assertions.push(
        ...assertObject(nestedPath, nestedValue as Record<string, unknown>, style, framework)
      );
    } else {
      assertions.push(assertPrimitive(nestedPath, nestedValue, style, framework));
    }
  }

  return assertions;
}

function assertPrimitive(
  path: string,
  value: unknown,
  style: AssertionStyle,
  framework: TestFramework
): string {
  const type = typeof value;

  if (style === ASSERTION_STYLE.TYPE_ONLY) {
    if (framework === TEST_FRAMEWORK.PLAYWRIGHT) {
      return `expect(typeof ${path}).toBe("${type}");`;
    } else {
      return `expect(${path}).to.be.a("${type}");`;
    }
  }

  // Exact value assertion
  if (framework === TEST_FRAMEWORK.PLAYWRIGHT) {
    if (type === "string") {
      return `expect(${path}).toBe("${escapeString(value as string)}");`;
    }
    return `expect(${path}).toBe(${JSON.stringify(value)});`;
  } else {
    if (type === "string") {
      return `expect(${path}).to.equal("${escapeString(value as string)}");`;
    }
    return `expect(${path}).to.equal(${JSON.stringify(value)});`;
  }
}

// Helpers

function slugify(str: string): string {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function camelCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, char) => char.toUpperCase())
    .replace(/^[A-Z]/, (char) => char.toLowerCase());
}

function escapeString(str: string): string {
  return str.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

export { TEST_FRAMEWORK, ASSERTION_STYLE };
